/**
 * Master Table Layout Configuration for Urban Spoon
 * Total: 30 Tables across 4 Ambiance Zones
 */

const TABLES = [
  // ZONE 1: Window Promenade (Tables 1 - 8) - Panoramic skyline & garden views
  {
    id: 1,
    number: 1,
    name: 'Table 1',
    zone: 'Window Promenade',
    capacity: 2,
    minGuests: 1,
    maxGuests: 2,
    shape: 'round',
    isWindow: true,
    isOutdoor: false,
    view: 'Skyline Window View',
    description: 'Intimate corner window table overlooking the city skyline. Perfect for couples.',
  },
  {
    id: 2,
    number: 2,
    name: 'Table 2',
    zone: 'Window Promenade',
    capacity: 2,
    minGuests: 1,
    maxGuests: 2,
    shape: 'round',
    isWindow: true,
    isOutdoor: false,
    view: 'Garden Promenade View',
    description: 'Candle-lit window table overlooking illuminated evening fountains.',
  },
  {
    id: 3,
    number: 3,
    name: 'Table 3',
    zone: 'Window Promenade',
    capacity: 4,
    minGuests: 2,
    maxGuests: 4,
    shape: 'rect',
    isWindow: true,
    isOutdoor: false,
    view: 'Panoramic Bay Window',
    description: 'Spacious bay window table with breathtaking sunset vistas.',
  },
  {
    id: 4,
    number: 4,
    name: 'Table 4',
    zone: 'Window Promenade',
    capacity: 4,
    minGuests: 2,
    maxGuests: 4,
    shape: 'rect',
    isWindow: true,
    isOutdoor: false,
    view: 'Panoramic Bay Window',
    description: 'Prime window seating with direct sightlines to the downtown lights.',
  },
  {
    id: 5,
    number: 5,
    name: 'Table 5',
    zone: 'Window Promenade',
    capacity: 2,
    minGuests: 1,
    maxGuests: 2,
    shape: 'round',
    isWindow: true,
    isOutdoor: false,
    view: 'Courtyard Glass View',
    description: 'Romantic 2-seater bathed in soft golden window light.',
  },
  {
    id: 6,
    number: 6,
    name: 'Table 6',
    zone: 'Window Promenade',
    capacity: 2,
    minGuests: 1,
    maxGuests: 2,
    shape: 'round',
    isWindow: true,
    isOutdoor: false,
    view: 'Courtyard Glass View',
    description: 'Cozy couple table with velvet seating by the grand glass facade.',
  },
  {
    id: 7,
    number: 7,
    name: 'Table 7',
    zone: 'Window Promenade',
    capacity: 4,
    minGuests: 2,
    maxGuests: 4,
    shape: 'rect',
    isWindow: true,
    isOutdoor: false,
    view: 'Avenue Window View',
    description: 'Four-seater table next to high arched glass windows.',
  },
  {
    id: 8,
    number: 8,
    name: 'Table 8',
    zone: 'Window Promenade',
    capacity: 4,
    minGuests: 2,
    maxGuests: 4,
    shape: 'rect',
    isWindow: true,
    isOutdoor: false,
    view: 'Corner Skyline View',
    description: 'Elevated corner window booth with expansive dual-angle views.',
  },

  // ZONE 2: Main Dining Hall (Tables 9 - 20) - Vibrant central culinary atmosphere
  {
    id: 9,
    number: 9,
    name: 'Table 9',
    zone: 'Main Dining Hall',
    capacity: 4,
    minGuests: 2,
    maxGuests: 4,
    shape: 'round',
    isWindow: false,
    isOutdoor: false,
    view: 'Culinary Open Kitchen View',
    description: 'Near the open culinary theater where master chefs prepare specialties.',
  },
  {
    id: 10,
    number: 10,
    name: 'Table 10',
    zone: 'Main Dining Hall',
    capacity: 4,
    minGuests: 2,
    maxGuests: 4,
    shape: 'round',
    isWindow: false,
    isOutdoor: false,
    view: 'Central Chandelier Ambiance',
    description: 'Centered directly under the crystalline chandelier.',
  },
  {
    id: 11,
    number: 11,
    name: 'Table 11',
    zone: 'Main Dining Hall',
    capacity: 6,
    minGuests: 3,
    maxGuests: 6,
    shape: 'rect',
    isWindow: false,
    isOutdoor: false,
    view: 'Grand Dining Hall View',
    description: 'Generous family dining table with plush walnut chairs.',
  },
  {
    id: 12,
    number: 12,
    name: 'Table 12',
    zone: 'Main Dining Hall',
    capacity: 6,
    minGuests: 3,
    maxGuests: 6,
    shape: 'rect',
    isWindow: false,
    isOutdoor: false,
    view: 'Grand Dining Hall View',
    description: 'Perfect for group dinners, reunions, and festive family meals.',
  },
  {
    id: 13,
    number: 13,
    name: 'Table 13',
    zone: 'Main Dining Hall',
    capacity: 4,
    minGuests: 2,
    maxGuests: 4,
    shape: 'rect',
    isWindow: false,
    isOutdoor: false,
    view: 'Wine Cellar Display',
    description: 'Adjacent to our climate-controlled glass wine cellar showcase.',
  },
  {
    id: 14,
    number: 14,
    name: 'Table 14',
    zone: 'Main Dining Hall',
    capacity: 4,
    minGuests: 2,
    maxGuests: 4,
    shape: 'rect',
    isWindow: false,
    isOutdoor: false,
    view: 'Wine Cellar Display',
    description: 'Refined sommelier-side table ideal for tasting menus.',
  },
  {
    id: 15,
    number: 15,
    name: 'Table 15',
    zone: 'Main Dining Hall',
    capacity: 2,
    minGuests: 1,
    maxGuests: 2,
    shape: 'round',
    isWindow: false,
    isOutdoor: false,
    view: 'Central Lounge View',
    description: 'Chic cocktail and dining table in the heart of the restaurant.',
  },
  {
    id: 16,
    number: 16,
    name: 'Table 16',
    zone: 'Main Dining Hall',
    capacity: 2,
    minGuests: 1,
    maxGuests: 2,
    shape: 'round',
    isWindow: false,
    isOutdoor: false,
    view: 'Central Lounge View',
    description: 'Intimate brass-accented round table for quick gourmet dining.',
  },
  {
    id: 17,
    number: 17,
    name: 'Table 17',
    zone: 'Main Dining Hall',
    capacity: 4,
    minGuests: 2,
    maxGuests: 4,
    shape: 'rect',
    isWindow: false,
    isOutdoor: false,
    view: 'Hall Centerpiece View',
    description: 'Classic four-top with comfortable mahogany armchairs.',
  },
  {
    id: 18,
    number: 18,
    name: 'Table 18',
    zone: 'Main Dining Hall',
    capacity: 4,
    minGuests: 2,
    maxGuests: 4,
    shape: 'rect',
    isWindow: false,
    isOutdoor: false,
    view: 'Hall Centerpiece View',
    description: 'Vibrant dining location surrounded by acoustic warmth.',
  },
  {
    id: 19,
    number: 19,
    name: 'Table 19',
    zone: 'Main Dining Hall',
    capacity: 6,
    minGuests: 3,
    maxGuests: 6,
    shape: 'rect',
    isWindow: false,
    isOutdoor: false,
    view: 'Executive Hall View',
    description: 'Long banquet style six-seater with polished marble top.',
  },
  {
    id: 20,
    number: 20,
    name: 'Table 20',
    zone: 'Main Dining Hall',
    capacity: 6,
    minGuests: 3,
    maxGuests: 6,
    shape: 'rect',
    isWindow: false,
    isOutdoor: false,
    view: 'Executive Hall View',
    description: 'Premium central party table designed for celebratory toasts.',
  },

  // ZONE 3: Royal Booths & Alcoves (Tables 21 - 26) - Cushioned privacy & luxury
  {
    id: 21,
    number: 21,
    name: 'Table 21',
    zone: 'Royal Booths',
    capacity: 6,
    minGuests: 4,
    maxGuests: 6,
    shape: 'booth',
    isWindow: false,
    isOutdoor: false,
    view: 'Private Velvet Alcove',
    description: 'Deep emerald velvet booth with secluded acoustic curtains.',
  },
  {
    id: 22,
    number: 22,
    name: 'Table 22',
    zone: 'Royal Booths',
    capacity: 6,
    minGuests: 4,
    maxGuests: 6,
    shape: 'booth',
    isWindow: false,
    isOutdoor: false,
    view: 'Private Velvet Alcove',
    description: 'Cushioned semi-private alcove for VIP meetings and intimate parties.',
  },
  {
    id: 23,
    number: 23,
    name: 'Table 23',
    zone: 'Royal Booths',
    capacity: 8,
    minGuests: 5,
    maxGuests: 8,
    shape: 'booth',
    isWindow: false,
    isOutdoor: false,
    view: 'Grand Royal Alcove',
    description: 'Extra-large curved leather booth for upscale birthday celebrations.',
  },
  {
    id: 24,
    number: 24,
    name: 'Table 24',
    zone: 'Royal Booths',
    capacity: 8,
    minGuests: 5,
    maxGuests: 8,
    shape: 'booth',
    isWindow: false,
    isOutdoor: false,
    view: 'Grand Royal Alcove',
    description: 'Spacious executive private dining booth with dedicated butler call.',
  },
  {
    id: 25,
    number: 25,
    name: 'Table 25',
    zone: 'Royal Booths',
    capacity: 6,
    minGuests: 4,
    maxGuests: 6,
    shape: 'booth',
    isWindow: false,
    isOutdoor: false,
    view: 'Heritage Gold Booth',
    description: 'Gold-leaf detailed booth with custom ambient pendant lighting.',
  },
  {
    id: 26,
    number: 26,
    name: 'Table 26',
    zone: 'Royal Booths',
    capacity: 6,
    minGuests: 4,
    maxGuests: 6,
    shape: 'booth',
    isWindow: false,
    isOutdoor: false,
    view: 'Heritage Gold Booth',
    description: 'Secluded luxury booth offering total discretion and quiet conversation.',
  },

  // ZONE 4: Terrace Starlight Lounge (Tables 27 - 30) - Open-air romantic starlight dining
  {
    id: 27,
    number: 27,
    name: 'Table 27',
    zone: 'Terrace Starlight',
    capacity: 2,
    minGuests: 1,
    maxGuests: 2,
    shape: 'round',
    isWindow: false,
    isOutdoor: true,
    view: 'Open Sky Terrace Balcony',
    description: 'Al fresco candle-lit table beneath fairy starlights and fresh breeze.',
  },
  {
    id: 28,
    number: 28,
    name: 'Table 28',
    zone: 'Terrace Starlight',
    capacity: 2,
    minGuests: 1,
    maxGuests: 2,
    shape: 'round',
    isWindow: false,
    isOutdoor: true,
    view: 'Open Sky Terrace Balcony',
    description: 'Couples terrace table overlooking the night skyline with heat lamps.',
  },
  {
    id: 29,
    number: 29,
    name: 'Table 29',
    zone: 'Terrace Starlight',
    capacity: 4,
    minGuests: 2,
    maxGuests: 4,
    shape: 'rect',
    isWindow: false,
    isOutdoor: true,
    view: 'Garden Pergola Terrace',
    description: 'Under the wisteria pergola on the terrace with ambient candlelight.',
  },
  {
    id: 30,
    number: 30,
    name: 'Table 30',
    zone: 'Terrace Starlight',
    capacity: 4,
    minGuests: 2,
    maxGuests: 4,
    shape: 'rect',
    isWindow: false,
    isOutdoor: true,
    view: 'Corner Sky Terrace',
    description: 'Prime outdoor terrace corner table with unobstructed starry views.',
  },
];

const TIME_SLOTS = [
  { id: 'lunch-1', label: '12:00 PM - 02:00 PM', period: 'Lunch' },
  { id: 'lunch-2', label: '02:00 PM - 04:00 PM', period: 'Lunch' },
  { id: 'dinner-1', label: '06:00 PM - 08:00 PM', period: 'Dinner' },
  { id: 'dinner-2', label: '08:00 PM - 10:00 PM', period: 'Dinner' },
  { id: 'dinner-3', label: '10:00 PM - 11:30 PM', period: 'Dinner' },
];

const ZONES = [
  { key: 'all', name: 'All Zones' },
  { key: 'Window Promenade', name: 'Window Promenade (1-8)' },
  { key: 'Main Dining Hall', name: 'Main Dining Hall (9-20)' },
  { key: 'Royal Booths', name: 'Royal Booths (21-26)' },
  { key: 'Terrace Starlight', name: 'Terrace Starlight (27-30)' },
];

module.exports = {
  TABLES,
  TIME_SLOTS,
  ZONES,
};
